#!/usr/bin/env python3
"""Convert TTF fonts to anti-aliased VLW (Processing smooth font) C arrays for LovyanGFX.

Usage:  uvx --with pillow python tools/make_vlw.py <dir with Inter-*.ttf> <output .h>

VLW layout (all integers 32-bit big-endian):
  header: glyph count, version (11), font size, 0, ascent, descent
  per glyph (sorted by code point): code point, height, width, x advance,
                                    top offset above baseline (dY), left offset (dX), 0
  then each glyph's width*height 8-bit alpha bitmap, in the same order.
Edit FONTS below to change faces, sizes or character sets.
"""
import struct
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ASCII = "".join(chr(c) for c in range(0x20, 0x7F))
TEXT = ASCII + "≈"   # + "≈" for the estimated-cost lines
DIGITS = " -.0123456789:"

# (C name, TTF file, pixel size, characters)
FONTS = [
    ("INTER_NUM50", "Inter-SemiBold.ttf", 50, DIGITS),   # gauge total
    ("INTER_NUM40", "Inter-SemiBold.ttf", 40, DIGITS),   # page values
    ("INTER_SB15",  "Inter-SemiBold.ttf", 15, ASCII),    # titles
    ("INTER_SB19",  "Inter-SemiBold.ttf", 19, ASCII),    # units, emphasised lines
    ("INTER_R16",   "Inter-Regular.ttf",  16, TEXT),    # secondary lines
    ("INTER_R13",   "Inter-Regular.ttf",  13, TEXT),    # hints, times
]


def vlw(ttf: Path, size: int, chars: str) -> bytes:
    font = ImageFont.truetype(str(ttf), size)
    ascent, descent = font.getmetrics()
    records, bitmaps = [], []
    for ch in sorted(set(chars)):
        advance = round(font.getlength(ch))
        left, top, right, bottom = font.getbbox(ch, anchor="ls")   # relative to the baseline origin
        w, h = max(0, right - left), max(0, bottom - top)
        if ch == " " or w == 0 or h == 0:
            w = h = 0
            left = top = 0
            data = b""
        else:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255, anchor="ls")
            data = img.tobytes()
        if not (w <= 255 and advance <= 255 and -128 <= left <= 127):
            raise ValueError(f"glyph {ch!r} at {size}px exceeds VLW field limits")
        records.append(struct.pack(">7i", ord(ch), h, w, advance, -top, left, 0))
        bitmaps.append(data)
    header = struct.pack(">6i", len(records), 11, size, 0, ascent, descent)
    return header + b"".join(records) + b"".join(bitmaps)


def c_array(name: str, data: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 20]) for i in range(0, len(data), 20)]
    return f"static const uint8_t {name}[{len(data)}] = {{\n  " + ",\n  ".join(rows) + "\n};\n"


def main() -> None:
    src, out = Path(sys.argv[1]), Path(sys.argv[2])
    parts = [
        "// Generated by tools/make_vlw.py from Inter 4.1 (https://github.com/rsms/inter) - do not edit.\n"
        "// Inter is licensed under the SIL Open Font License 1.1: see fonts/Inter-LICENSE.txt.\n"
        "#pragma once\n#include <stdint.h>\n\n"
    ]
    total = 0
    for name, ttf, size, chars in FONTS:
        data = vlw(src / ttf, size, chars)
        total += len(data)
        parts.append(f"// {ttf} {size}px, {len(set(chars))} glyphs\n" + c_array(name, data) + "\n")
        print(f"{name:12} {ttf:20} {size:3}px {len(data):6} bytes")
    out.write_text("".join(parts))
    print(f"total {total} bytes -> {out}")


if __name__ == "__main__":
    main()
